In [3]:
from unfold import Unfold
import bw2io, bw2data, bw2calc

In [7]:
import brightway2 as bw
bw.projects.set_current("new4")

In [8]:
u = Unfold("test.zip")

The data package contains the following scenarios:
+-----+--------------------------------+-------------+
| No. |            Scenario            | Description |
+-----+--------------------------------+-------------+
|  0  | ecoinvent_remind_SSP2-NPi_2005 |     test    |
|  1  | ecoinvent_remind_SSP2-NPi_2010 |     test    |
+-----+--------------------------------+-------------+

To unfold all scenarios, `unfold()`.
To unfold a specific scenario, `unfold(scenarios=[1,])`.


In [9]:
u.unfold()

The following databases are necessary to unfold the scenarios:
+-----+----------------------+--------------+---------+
| No. |      Dependency      | System model | Version |
+-----+----------------------+--------------+---------+
|  1  | ecoinvent 3.8 cutoff |     test     |   test  |
|  2  |      biosphere3      |              |         |
+-----+----------------------+--------------+---------+

The following databases are available in your project:
+-----+--------------------------------+
| No. |            Database            |
+-----+--------------------------------+
|  1  |           biosphere3           |
|  2  |      ecoinvent 3.8 cutoff      |
|  3  |      ecoinvent 3.7 cutoff      |
|  4  |      ecoinvent 3.6 cutoff      |
|  5  |             test1              |
|  6  |             test2              |
|  7  | ecoinvent_remind_SSP2-NPi_2005 |
|  8  | ecoinvent_remind_SSP2-NPi_2010 |
|  9  |           test_super           |
+-----+--------------------------------+



Indicate the database number for dependency 1:  2
Indicate the database number for dependency 2:  1


Getting activity data


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19565/19565 [00:00<00:00, 293012.11it/s]


Adding exchange data to activities


100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 629959/629959 [00:34<00:00, 18040.63it/s]


Filling out exchange data


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19565/19565 [00:02<00:00, 7831.25it/s]


Getting activity data


100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4427/4427 [00:00<00:00, 382636.14it/s]


Adding exchange data to activities


0it [00:00, ?it/s]


Filling out exchange data


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4427/4427 [00:00<00:00, 5541087.38it/s]


Extracting additional inventories...
Generating database for scenario ecoinvent_remind_SSP2-NPi_2005...
Generating database for scenario ecoinvent_remind_SSP2-NPi_2010...
Writing database for scenario ecoinvent_remind_SSP2-NPi_2005...
Database ecoinvent_remind_SSP2-NPi_2005 already exists: it will be overwritten.
Vacuuming database 


Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:28


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 11:52:39
  Finished: 03/14/2023 11:53:08
  Total time elapsed: 00:00:28
  CPU %: 97.00
  Memory %: 17.42
Created database: ecoinvent_remind_SSP2-NPi_2005
Writing database for scenario ecoinvent_remind_SSP2-NPi_2010...
Database ecoinvent_remind_SSP2-NPi_2010 already exists: it will be overwritten.
Vacuuming database 


Writing activities to SQLite3 database:
0% [##############################] 100% | ETA: 00:00:00
Total time elapsed: 00:00:29


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 11:55:25
  Finished: 03/14/2023 11:55:54
  Total time elapsed: 00:00:29
  CPU %: 97.60
  Memory %: 18.79
Created database: ecoinvent_remind_SSP2-NPi_2010


In [3]:
from unfold import Fold
import bw2io, bw2data

In [4]:
bw2data.projects.set_current("new")
f = Fold()

In [5]:
m = f.fold()

Give a name for this datapackage:  test
Give a short description for this datapackage:  test


The following databases are available in your project:
+-----+---------------------------------------+
| No. |                Database               |
+-----+---------------------------------------+
|  1  |               biosphere3              |
|  2  |          ecoinvent 3.8 cutoff         |
|  3  |             carculator_lci            |
|  4  |          carculator_lci_truck         |
|  5  |      carculator import20.11.2021      |
|  6  |           nuclear fuel chain          |
|  7  |          nuclear electricity          |
|  8  |        nuclear electricity SMR        |
|  9  |              wave_energy              |
|  10 |                RTE_2020               |
|  11 |                RTE_2030               |
|  12 |                RTE_2040               |
|  13 |                RTE_2050               |
|  14 |              HDfuels_2035             |
|  15 |          HDfuels_2035_EU_only         |
|  16 |                carina_1               |
|  17 |        premise_remind_ssp

Indicate the no. of the reference database:  2
Indicate the system model of ecoinvent 3.8 cutoff:  test
Indicate the version of ecoinvent 3.8 cutoff:  test
Indicate the no. of the databases you would like to fold, separated by a comma:  21, 22
Give a short description for ecoinvent_remind_SSP2-NPi_2005:  test
Give a short description for ecoinvent_remind_SSP2-NPi_2010:  test


Extracting source database...
Done!
Extracting databases to fold...
Done!

The database biosphere3 is an external dependency. It will be extracted automatically.
Building scenario factor file...
Data package saved at test.zip


In [ ]:
f = Fold()

f.fold(
    package_name="Test_package",
    package_description="some description",
    source="ecoinvent 3.8 cutoff",
    system_model="cut off",
    version="3.8",
    databases_to_fold=["amelie_1","amelie_2"],
    descriptions=["a database from my thesis", "another database from my thesis"],
)

In [ ]:
for ds in f.source["database"]:
    if "reference product" not in ds:
        print(ds["name"])

In [ ]:
check_mandatory_fields(f.source["database"])

In [ ]:
list_unique_acts = []
for ds in f.source["database"]:
    list_unique_acts.extend([
        (
            f.rev_dependency_mapping.get(exchange.get("input"), (None,))[0],
            f.rev_dependency_mapping.get(exchange.get("input"), (None, None))[1],
            f.rev_dependency_mapping.get(exchange.get("input"), (None,))[-1],
            f.rev_dependency_mapping.get(exchange.get("input"), (None, None, None))[2],
            exchange["unit"],
            exchange["type"],
        )
        for exchange in ds["exchanges"]
    ])

In [ ]:
f.source["database"][0]["exchanges"][0]["input"]

In [1]:
import brightway2 as bw
bw.projects.set_current("new4")

In [28]:
import yaml

fp = "/Users/romain/GitHub/unfold/tests/fixture/reference_database.yaml"
with open(fp, "r") as stream:
    db = yaml.load(stream, Loader=yaml.FullLoader)
    
fp = "/Users/romain/GitHub/unfold/tests/fixture/db A.yaml"

with open(fp, "r") as stream:
    db_a = yaml.load(stream, Loader=yaml.FullLoader)
    
fp = "/Users/romain/GitHub/unfold/tests/fixture/db B.yaml"

with open(fp, "r") as stream:
    db_b = yaml.load(stream, Loader=yaml.FullLoader)

In [29]:
bw.Database("reference_database").write(db)
bw.Database("db A").write(db_a)
bw.Database("db B").write(db_b)

Writing activities to SQLite3 database:
0% [####] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Writing activities to SQLite3 database:


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 17:10:14
  Finished: 03/14/2023 17:10:14
  Total time elapsed: 00:00:00
  CPU %: 114.10
  Memory %: 2.24


0% [####] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 17:10:14
  Finished: 03/14/2023 17:10:14
  Total time elapsed: 00:00:00
  CPU %: 115.80
  Memory %: 2.29


Writing activities to SQLite3 database:
0% [####] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 17:10:15
  Finished: 03/14/2023 17:10:15
  Total time elapsed: 00:00:00
  CPU %: 101.30
  Memory %: 2.33


In [34]:
lca = bw.LCA({bw.get_activity(("reference_database", "activity A")): 1})
lca.lci()
lca.supply_array

array([ 1.        ,  6.18367386, 12.11224588,  0.        ])

In [35]:
lca = bw.LCA({bw.get_activity(("db A", "activity A")): 1})
lca.lci()
original_supply_A = lca.supply_array
original_supply_A

/opt/homebrew/Caskroom/miniforge/base/envs/unfold/lib/python3.10/site-packages/bw2calc/lca.py:228: UserWarning: No biosphere flows found. No inventory results can be calculated, `lcia` will raise an error
  warnings.warn("No biosphere flows found. No inventory results can "


array([ 1.        , 10.62500066, 19.56250163,  0.        ])

In [36]:
lca = bw.LCA({bw.get_activity(("db B", "activity A")): 1})
lca.lci()
original_supply_B = lca.supply_array
original_supply_B

/opt/homebrew/Caskroom/miniforge/base/envs/unfold/lib/python3.10/site-packages/bw2calc/lca.py:228: UserWarning: No biosphere flows found. No inventory results can be calculated, `lcia` will raise an error
  warnings.warn("No biosphere flows found. No inventory results can "


array([ 1.        , 10.56250097, 19.1562522 ,  0.        ])

In [38]:
from unfold import Fold

In [40]:
f = Fold()

In [43]:
f.fold(
    package_name="test",
    package_description="description of test",
    source="reference_database",
    system_model="cutoff",
    version="2.0",
    databases_to_fold=["db A", "db B"],
    descriptions=["this is db A", "this is db B"]
)

Extracting source database...
Done!
Extracting databases to fold...
Done!
Building scenario factor file...
Data package saved at test.zip


In [44]:
from unfold import Unfold

In [50]:
u = Unfold("test.zip").unfold(
    dependencies={
        "reference_database": "reference_database"
    }
)

The data package contains the following scenarios:
+-----+----------+--------------+
| No. | Scenario | Description  |
+-----+----------+--------------+
|  0  |   db A   | this is db A |
|  1  |   db B   | this is db B |
+-----+----------+--------------+

To unfold all scenarios, `unfold()`.
To unfold a specific scenario, `unfold(scenarios=[1,])`.
Getting activity data


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 36711.63it/s]


Adding exchange data to activities


100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [00:00<00:00, 7065.88it/s]


Filling out exchange data


100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 37365.74it/s]

Extracting additional inventories...
Generating database for scenario db A...
Generating database for scenario db B...
Writing database for scenario db A...
Database db A already exists: it will be overwritten.



Writing activities to SQLite3 database:
0% [####] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00
Writing activities to SQLite3 database:


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 17:18:48
  Finished: 03/14/2023 17:18:48
  Total time elapsed: 00:00:00
  CPU %: 111.30
  Memory %: 1.87
Created database: db A
Writing database for scenario db B...
Database db B already exists: it will be overwritten.


0% [####] 100% | ETA: 00:00:00
Total time elapsed: 00:00:00


Title: Writing activities to SQLite3 database:
  Started: 03/14/2023 17:18:48
  Finished: 03/14/2023 17:18:48
  Total time elapsed: 00:00:00
  CPU %: 110.40
  Memory %: 1.93
Created database: db B


In [54]:
import numpy as np
lca = bw.LCA({bw.get_activity(("db A", "activity A")): 1})
lca.lci()
new_supply_A = lca.supply_array
np.allclose(original_supply_A, new_supply_A)

True

In [55]:
import numpy as np
lca = bw.LCA({bw.get_activity(("db B", "activity A")): 1})
lca.lci()
new_supply_B = lca.supply_array
np.allclose(original_supply_B, new_supply_B)

True